### PR TITLE
Tc006 Margie has been completed

### PR DESCRIPTION
**Pull request by maggan1968**

### CODE REVIEW

**Comment by maggan1968** [comment]
hi guys

**Comment by AzizaMir26** [comment]
nice

**Comment by maggan1968** [comment]
do you see my merge?

**Comment by AzizaMir26** [comment]
yes

**Comment by NurcanGulkan** [comment]
hi ,

**Comment by AzizaMir26** [comment]
but i did it in my branch so no issues if its not on master i guess

**Comment by NurcanGulkan** [comment]
we are doing good

**Comment by AzizaMir26** [comment]
margie do u see my branch
??

**Comment by nilufarmirzoeva** [comment]
Hello

**Comment by nilufarmirzoeva** [comment]
Do you see my comment?

**Comment by AzizaMir26** [comment]
@IgorL1991  try to merge here

**Comment by IgorL1991** [comment]
Test

**Comment by RaikaMogultay** [comment]
Welcome

**Pull request merged**
